Ready for review
michel0323/fullstack-starter pull request #1
Opened 2022-08-30 00:02 UTC by michel0323

2022-09-01 06:12 UTC, michel0323 commented
I welcome feedback. Thanks!

2022-09-03 00:09 UTC, sofiac-developer requested changes

2022-09-03 00:09 UTC, sofiac-developer commented on starter/src/test/java/com/starter/fullstack/dao/InventoryDAOTest.java
> +    @Mock private MongoTemplate mockMongoTemplate;
You shouldn't use a mock for mongo template. Utilize the mongo template set up in this test. 
Also you shouldn't remove anything from the test. Any lines here that are red should be added back. This file should only be adding to it, not removing

2022-09-03 00:09 UTC, sofiac-developer commented on starter/src/test/java/com/starter/fullstack/dao/InventoryDAOTest.java
> +import org.mockito.Mock;
You shouldn't need Mockito for this test.

2022-09-03 00:09 UTC, sofiac-developer commented on starter/src/main/java/com/starter/fullstack/dao/InventoryDAO.java
> +    inventory.setId(null);
Looks good

2022-09-12 23:46 UTC, jinlin0 commented on starter/src/test/java/com/starter/fullstack/dao/InventoryDAOTest.java
> +        assertNotNull(actual.getName());
add an assert for the inventory id

2022-09-20 05:30 UTC, merged